version: '3'

services:
 database:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: laravel 
     MYSQL_DATABASE: laravel_db
     MYSQL_USER: laravel
     MYSQL_PASSWORD: password
   ports:
     - 3306:3306